apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:14.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: api-configmap
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres-secret
        - name: POSTGRES_USER
          valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: postgres-secret