# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.2.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: ./src
        # Path to the Dockerfile
        file: ./src/Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: |
          dverazs/kube-news2:latest
          dverazs/kube-news2:${{github.run_number}}

